# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.18.x'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r test-requirements.txt
        python -m pip install -e .
    - name: Install libraries from PySCF
      run: |
        cd lib; mkdir build; cd build
        cmake ..
        make
        cd ../..
    - name: Install libcint
      run: |
        cd lib/libcint; mkdir build; cd build
        cmake ..
        make
        cd ../../..
    - name: Install libxc
      run: |
        cd submodules/libxc
        python setup.py install
        cd ../..
    - name: Run test
      run: |
        cd dqc/test
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
        flags: unittests # optional
        name: codecov-xitorch # optional
