name: Build wheels

on: [ push ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
      fail-fast: false
    env:
      DQC_BUILD: 1

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install cython
        run: |
          python -m pip install Cython

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.11.0

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD_LINUX: python -m pip install cmake; yum install -y openblas-devel.x86_64 gcc
          CIBW_BEFORE_BUILD_MACOS: python -m pip install cmake; brew install openblas gcc
          CIBW_ARCHS: x86_64
          CIBW_BUILD: cp3*-*
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ENVIRONMENT: "DQC_BUILD=1"
          CIBW_BEFORE_TEST: python -m pip install pytest
          CIBW_TEST_COMMAND: python -m pytest {project}/dqc/test/test_ks.py::test_uks_energy_same_as_rks
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

      - uses: actions/upload-artifact@v2
        with:
          name: python-wheels
          path: ./wheelhouse/*.whl

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest

    steps:
      - name: Download Python wheels
        uses: actions/download-artifact@v2
        with:
          name: python-wheels
          path: dist/

      - name: Publish distribution to Test PyPI
        if: ${{ !(startsWith(github.ref, 'refs/tags')) }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
